name: Build proxmox-service-discovery

on:
  push:
    branches:
      - main  # Сборка запускается только при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]  # Матрица для архитектур amd64 и arm64

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go 1.31
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # Step 3: Set GOARCH environment variable
    - name: Set architecture
      run: echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

    # Step 4: Cache Go modules (optional, speeds up builds)
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.goarch }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.goarch }}-

    # Step 5: Install dependencies
    - name: Install dependencies
      run: go mod download

    # Step 6: Build the proxmox-service-discovery application for the specified architecture
    - name: Build proxmox-service-discovery
      run: go build -v -o proxmox-service-discovery-${{ matrix.goarch }} ./...

    # Step 7: Upload the build as an artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: proxmox-service-discovery-${{ matrix.goarch }}
        path: ./proxmox-service-discovery-${{ matrix.goarch }}
