name: Build, Tag, and Release proxmox-service-discovery

on:
  push:
    branches:
      - main

jobs:
  version:
    outputs:
      app_version: ${{ steps.version.outputs.new_tag }}
      changelog: ${{ steps.version.outputs.changelog }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set architecture
      run: echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: go mod download

    - name: Build proxmox-service-discovery
      run: go build -o proxmox-service-discovery-linux-${{ matrix.goarch }}

    - name: Package binary into a ZIP file
      run: zip proxmox-service-discovery-linux-${{ matrix.goarch }}.zip proxmox-service-discovery-linux-${{ matrix.goarch }}

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxmox-service-discovery-linux-${{ matrix.goarch }}.zip
        path: ./proxmox-service-discovery-linux-${{ matrix.goarch }}.zip

  release:
    needs: 
      - version
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download ZIP artifacts
      uses: actions/download-artifact@v4
      with:
        name: proxmox-service-discovery-linux
        path: proxmox-service-discovery-linux*.zip

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ needs.version.outputs.app_version }}
        name: Release ${{ needs.version.outputs.app_version }}
        body: ${{ needs.version.outputs.changelog }}
        generateReleaseNotes: true

    - name: Upload Linux AMD64 ZIP artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./proxmox-service-discovery-linux-amd64.zip
        asset_name: proxmox-service-discovery-linux-amd64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux ARM64 ZIP artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./proxmox-service-discovery-linux-arm64.zip
        asset_name: proxmox-service-discovery-linux-arm64.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
